### ISSUE TITLE
how to use csv dataset

### ISSUE THREAD

**Issue by hoseinchamany** [Mujadded/knn-with-tensorflow#1]
i have my own dataset, how to use it

**Comment by Mujadded** [comment]
` filename_queue = tf.train.string_input_producer(["file0.csv", "file1.csv"])

reader = tf.TextLineReader()
key, value = reader.read(filename_queue) `

There is a good example in Tensorflow documentation please see that: [documentation_link](https://www.tensorflow.org/api_guides/python/reading_data)
